### ISSUE TITLE
start_dev.sh throw an error

### ISSUE THREAD

**Issue by rxrxrxrx** [draffle-io/draffle#13]
Hi,

I cloned your repo,
when I launch start_dev it process and I get : 

86f5xSDrue8Zz4QfuMErURN3o393L72zA1J2WRsYeTGB
Done
Creating sample mints, accounts, and funding them...
error: No such file or directory (os error 2)

So this line doesnt works :

 spl-token create-token ${SCRIPT_PATH}/sample_accounts/prize-nft1-keypair.json --decimals 0

Any idea why? 
This file exist : 

cat sample_accounts/dev-mint-keypair.json                      
[202,210,198,146,99,182,174,236,139,7,250,6,111,0,136,203,110,125,184,225,59,167,79,144,155,4,112,136,151,122,145,39,14,182,43,62,84,157,230,147,96,25,90,5,141,7,169,161,207,231,224,130,176,66,93,204,89,230,26,59,90,233,149,105]

Of course if I start the front end I get an error, I assume its because no raffle are created or something like this. 
pretty sure my issue is simple, but I would appreciate some help

**Comment by moneytoad888** [comment]
Odd, do you run the script from the root directory?
scripts/start_dev.sh?
